remote_theme: lorepirri/cayman-blog

url: "intrigus.org"
title: "Intrigus' Security Lab"

author: "intrigus"
#excerpt_separator: <!--more-->

github:
  owner_name: "intrigus-lgtm"
  owner_url: "https://github.com/intrigus-lgtm"
  is_project_page: false

twitter:
  username: "intrigus_"

header_page_refs: ["research", "advisories", "about", "contact"]

linkToCodeQlGithub: "[CodeQL](https://github.com/github/codeql)"

description: "A tiny contribution on securing the world's software"

permalink: pretty
