remote_theme: lorepirri/cayman-blog

url: "https://intrigus.org"
title: "Intrigus' Security Lab"

author: "intrigus"
#excerpt_separator: <!--more-->

twitter:
  username: "intrigus_"

header_page_refs: ["research", "advisories", "about", "contact"]

linkToCodeQlGithub: "[CodeQL](https://github.com/github/codeql)"

description: "A tiny contribution on securing the world's software"

permalink: pretty

image: "assets/images/social-card-graphic.png"
