nand-gates-visualization.svg: nand-gates-visualization.tex
	dvilualatex nand-gates-visualization.tex && dvisvgm --font-format=woff nand-gates-visualization.dvi && \
	rm nand-gates-visualization.dvi && rm nand-gates-visualization.log && rm nand-gates-visualization.aux